version: '2'
 
services:
    db:
      image: mysql:5.7.25
      environment:
                - MYSQL_DATABASE=db
                - MYSQL_USER=admin
                - MYSQL_PASSWORD=pw
                - MYSQL_ROOT_PASSWORD=pw
      volumes:
            - ./db:/var/lib/mysql
      ports:
            - "3306:3306"
    phpmyadmin:
     image: phpmyadmin/phpmyadmin
     depends_on:
            - db
     environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: admin
            MYSQL_PASSWORD: pw
            MYSQL_ROOT_PASSWORD: pw
     ports:
            - "80:80"
     links:
            # for mysql container
            - "db:db"
volumes:
    db:
        driver: "local"